#!/usr/bin/env zsh

_call_navi() {
  local selected
  if selected="$(printf "$(navi --print </dev/tty)")"; then
    LBUFFER="$selected"
  fi
  zle redisplay
}

zle -N _call_navi

bindkey '^f' _call_navi
